name: Certora

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        conf:
          - DllFifo
          - DllSimple

    steps:
      - uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install certora
        run: pip install certora-cli

      - name: Install solc
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.17/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc-0.8.17

      - name: Verify rule ${{ matrix.script }}
        run: |
          echo "key length" ${#CERTORAKEY}
          make -C certora munged-simple
          make -C certora munged-fifo
          certoraRun certora/confs/${{ matrix.conf }}.conf
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
